name: Run github action from workflow manager

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  github-workflow-namager:
    runs-on: ubuntu-latest
    name: Select the appropiate workflow based on the language
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v2
      - name: Check out workflow repo
        uses: actions/checkout@v2
        with:
          repository: crunchyroll/data-compliance-scripts
          path: 'workflow-manager-repo'
      - name: Print current directory
        run: ls -la
      - name: Print workflow manager repo
        run: ls -la workflow-manager-repo
      - name: checkout-repo-github-action
        uses: './workflow-manager-repo/.github/actions/security'
        id: select-language
        with: 
          language: 'Python'
      - name: Remove workflow repo
        run: rm -rf workflow-manager-repo && git status
# # PR auto merge
#       - name: "Get date"
#         id: get-date
#         run: echo "::set-output name=DATE::$(/bin/date -u "+%F")"
#       - name: Create pull request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           branch: "branchname"
#           delete-branch: true
#           commit-message: ":lock_with_ink_pen: Message"
#           title: ":lock_with_ink_pen: Message"
#           body: |
#             Revision made as of ${{ steps.get-date.outputs.DATE }}.
#             This PR is auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
#           # labels: |
#           #   Type: enhancement
