name: Run github action from workflow manager

on: [pull request]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  github-workflow-namager:
    runs-on: ubuntu-latest
    name: Select the appropiate workflow based on the language
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: checkout-repo-github-action
        uses: './.github/actions/security'
        id: update-db
        with: 
            maxmind-apikey: ${{ secrets.MaxmindAPIKey }}
            destination-filename: 'data/GeoIP2-Country.mmdb'

      - name: "Get date"
        id: get-date
        run: echo "::set-output name=DATE::$(/bin/date -u "+%F")"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "branchname"
          delete-branch: true
          commit-message: ":lock_with_ink_pen: Message"
          title: ":lock_with_ink_pen: Message"
          body: |
            Revision made as of ${{ steps.get-date.outputs.DATE }}.
            This PR is auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            Type: enhancement
